version: "2.1"
services:

## Starts up mySQL server for ubyssey.ca and Dispatch
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ubyssey
      MYSQL_USER: root
      MYSQL_PASSWORD: ubyssey
      MYSQL_DATABASE: ubyssey
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ubyssey --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 20
    container_name: ubyssey_db

## Starts up Django server for ubyssey.ca and Dispatch
  django:
    image: keeganlandrigan/ubyssey-dev:0.03
    ports:
      - "8000:8000"
      - "4444:4444"
    depends_on:
      db:
        condition: service_healthy
    container_name: ubyssey-dev
    stdin_open: true
    tty: true


volumes:
  data: {}